[package]
authors = [ "MaidSafe Developers <dev@maidsafe.net>" ]
description = "A secured storage DHT"
documentation = "https://docs.rs/sn_routing"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "sn_routing"
readme = "README.md"
repository = "https://github.com/maidsafe/sn_routing"
version = "0.43.2"
edition = "2018"

[dependencies]
bincode = "1.2.1"
bls_dkg = "~0.3.1"
bls_signature_aggregator = "~0.2.0"
bytes = "~1.0.1"
futures = "~0.3.6"
hex_fmt = "~0.3.0"
itertools = "~0.9.0"
lru_time_cache = "~0.11.0"
# qp2p = "~0.9.22"
qp2p = { path = "../qp2p" }
rand = "~0.7.3"
rand_chacha = "~0.2.2"
thiserror = "1.0.23"
xor_name = "1.1.0"
resource_proof = "0.8.0"
# sn_messaging = "~4.0.0"
sn_messaging = { git = "https://github.com/oetyng/sn_messaging", branch = "all-acc-in-routing" }
# sn_messaging = { path = "../sn_messaging" }
# sn_data_types = "~0.14.3"
sn_data_types = { git = "https://github.com/oetyng/sn_data_types", branch = "remove-msgenvelope" }
# sn_data_types = { path = "../sn_data_types" }

  [dependencies.bls]
  package = "threshold_crypto"
  version = "~0.4.0"

  [dependencies.ed25519-dalek]
  version = "1.0.1"
  features = [ "serde" ]

  [dependencies.serde]
  version = "1.0.117"
  features = [ "derive" ]

  [dependencies.tiny-keccak]
  version = "2.0.2"
  features = [ "sha3" ]

  [dependencies.tokio]
  version = "~0.2.24"
  features = [ "sync", "time", "rt-util" ]

  [dependencies.tracing]
  version = "~0.1.22"
  default-features = false
  features = [ "log", "std" ]

[dev-dependencies]
anyhow = "1"
assert_matches = "1.3"
proptest = "0.10.1"
structopt = "~0.3.17"
tracing-appender = "~0.1.2"
tracing-subscriber = "~0.2.15"
yansi = "~0.5.0"

  [dev-dependencies.rand]
  version = "~0.7.3"
  features = [ "small_rng" ]

  [dev-dependencies.tokio]
  version = "~0.2.24"
  features = [ "stream", "udp" ]