[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A secured storage DHT"
documentation = "https://docs.rs/routing"
homepage = "https://maidsafe.net"
license = "GPL-3.0"
name = "routing"
readme = "README.md"
repository = "https://github.com/maidsafe/routing"
version = "0.37.0"
edition = "2018"

[dependencies]
bincode = "1.2.1"
bls = { package = "threshold_crypto", version = "~0.3.2" }
bls_dkg = { git = "https://github.com/maidsafe/BLS-DKG" }
bytes = "~0.5.4"
crossbeam-channel = "~0.4.2"
ctrlc = { version = "3", optional = true, features = ["termination"] }
ed25519-dalek = { version = "1.0.0-pre.3", features = ["serde"] }
env_logger = { version = "~0.7.1", optional = true }
err-derive = "~0.2.4"
fake_clock = "~0.3.0"
fxhash = "~0.2.1"
hex_fmt = "~0.3.0"
itertools = "~0.9.0"
lazy_static = { version = "1", optional = true }
log = "~0.4.8"
lru_time_cache = "~0.10.0"
mock-quic-p2p = { git = "https://github.com/maidsafe/quic-p2p", optional = true }
parsec = { git = "https://github.com/maidsafe/parsec" }
quic-p2p = { version = "~0.7.0", features = ["upnp"] }
rand = "~0.7.3"
# rand in the versions used by the threshold-crypto crate
rand_crypto = { package = "rand", version = "~0.6.5" }
rand_core = "~0.5.1"
rand_os = "~0.2.2"
rand_xorshift = "~0.2.0"
serde = { version = "1.0.111", features = ["derive" ,"rc"] }
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
xor_name = "1"

[dev-dependencies]
env_logger = "~0.7.1"
structopt = "~0.3.9"

[features]
mock_base = [
    "lru_time_cache/fake_clock",
    "mock-quic-p2p",
    "parsec/mock",
    "parsec/malice-detection",
    "ctrlc",
    "lazy_static",
    "bls/use-insecure-test-only-mock-crypto",
    "env_logger",
]
mock = ["mock_base"]
