on: [push, pull_request]
name: Real Parsec tests

jobs:
  test:
    name: TestRealParsec
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      # Install Rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      # Run tests
      - name: Test mock_base
        run: cargo test --release --features mock_base
